### ISSUE TITLE
Is Node.js used during the build?

### ISSUE THREAD

**Issue by webern** [ikatson/rqbit#293]
I didn't notice prerequisites for the `cargo build --release` command in the readme.

```
error: failed to run custom build command for `librqbit v7.1.0-beta.1 (/Users/someone/repos/rqbit/crates/librqbit)`

Caused by:
  process didn't exit successfully: `/Users/someone/repos/rqbit/target/release/build/librqbit-b87b856c843a3e3e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=webui/src

  > esbuild@0.21.5 postinstall /Users/someone/repos/rqbit/crates/librqbit/webui/node_modules/esbuild
  > node install.js

  added 230 packages from 214 contributors and audited 270 packages in 27.952s

  46 packages are looking for funding
    run `npm fund` for details

  found 0 vulnerabilities



  --- stderr
  thread 'main' panicked at crates/librqbit/build.rs:52:37:
  called `Result::unwrap()` on an `Err` value: "npm run build" failed

  stderr: /Users/someone/repos/rqbit/crates/librqbit/webui/node_modules/typescript/lib/_tsc.js:92
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

  SyntaxError: Unexpected token '?'
      at wrapSafe (internal/modules/cjs/loader.js:1072:16)
      at Module._compile (internal/modules/cjs/loader.js:1122:27)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Module.require (internal/modules/cjs/loader.js:1044:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/Users/someone/repos/rqbit/crates/librqbit/webui/node_modules/typescript/lib/tsc.js:8:18)
      at Module._compile (internal/modules/cjs/loader.js:1158:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! rqbit-webui@ build: `tsc --noEmit && vite build && node post-build`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the rqbit-webui@ build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /Users/someone/.npm/_logs/2024-12-16T02_25_57_059Z-debug.log


  stdout:
  > rqbit-webui@ build /Users/someone/repos/rqbit/crates/librqbit/webui
  > tsc --noEmit && vite build && node post-build


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAIL: 101
```

**Comment by ikatson** [comment]
> Is Node.js used during the build?

Yes, if "webui" feature is enabled. It's enabled by default for rqbit binary, but not for librqbit

**Comment by JeromeSchmied** [comment]
to disable it, you could do the following: `cargo install rqbit --no-default-features --features rust-tls,postgres`

where `--no-default-features` disables `native-tls`, `postgres`and __`webui`__
and you can then reenable the features you like with `--features <feature1>,<feature2>,<..>`

**Comment by ikatson** [comment]
Thanks @JeromeSchmied for helping here, closing
