### ISSUE TITLE
Crash on FreeBSD: thread 'tokio-runtime-worker' panicked at crates/librqbit/src/chunk_tracker.rs:48:14

### ISSUE THREAD

**Issue by yonas** [ikatson/rqbit#54]
Able to compile from #52, but a crash occurs when after adding a torrent. Tested using the webui.

```
$ rqbit --http-api-listen-addr 0.0.0.0:3030 server start /tmp
2023-12-12T17:53:12.550272Z  INFO librqbit::session: Listening on 0.0.0.0:4240 for incoming peer connections
2023-12-12T17:53:12.550364Z  INFO librqbit_dht::persistence: will store DHT routing table periodically filename="/home/yonas/.cache/dht/dht.json"
2023-12-12T17:53:12.550657Z  INFO librqbit_dht::persistence: loaded DHT routing table from filename="/home/yonas/.cache/dht/dht.json"
2023-12-12T17:53:12.550765Z  INFO librqbit_dht::dht: DHT listening on 0.0.0.0:14697
2023-12-12T17:53:12.550791Z  INFO librqbit_dht::dht: starting up DHT with peer id 2d7251303030312d4fb44aab92dbc00126a2be41
2023-12-12T17:53:12.550965Z  INFO librqbit::session: will use "/home/yonas/.local/share/session/session.json" for session persistence
2023-12-12T17:53:12.551460Z  INFO librqbit::http_api: starting HTTP server addr=0.0.0.0:3030
2023-12-12T17:54:21.247373Z  INFO torrent{id=0}:initialize_and_start: librqbit::torrent_state::initializing: Doing initial checksum validation, this might take a while...
2023-12-12T17:54:21.249468Z  INFO torrent{id=0}:initialize_and_start: librqbit::torrent_state::initializing: Initial check results: have 0, needed 612.4Ki
thread 'tokio-runtime-worker' panicked at crates/librqbit/src/chunk_tracker.rs:48:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'files/usr/local/bin/rqbit --htt…' terminated by signal SIGABRT (Abort)
```

**Comment by ikatson** [comment]
That's strange.
Is it a particular torrent that is causing this or any torrent? Did you change the selected files or left all selected?
Would be cool if you can share the infohash at least to see if I can repro.

Haven't seen this unwrap crash ever before. It might be FreeBSD specific, but also likely it's a general bug.

**Comment by nwgat** [comment]
i got this error too in a alpine docker container downloading ubuntu-23.10.1-desktop-amd64.iso (1).torrent

**Comment by nwgat** [comment]
i think its related to `--http-api-listen-addr`  function as it didn't happend when i ran it out of the box

**Comment by ikatson** [comment]
If this wasn't fixed yet it should be fixed in [v5.6.0-beta.0](https://github.com/ikatson/rqbit/releases/tag/v5.6.0-beta.0)

**Comment by yonas** [comment]
@ikatson It works, thanks! :tada:

**Comment by ikatson** [comment]
@yonas was it still broken before 5.6.0? Can you share the torrent it was broken on?

I installed freebsd (aarch64) into a VM and couldn't repro no matter what I tried. That was before making the tee changes for 5.6.0.

**Comment by yonas** [comment]
> was it still broken before 5.6.0?

It was broken for the latest git commit when I made that post.

> Can you share the torrent it was broken on?

The bug appeared irrespective of the torrent.

> I installed freebsd (aarch64) into a VM and couldn't repro no matter what I tried. That was before making the tee changes for 5.6.0.

I'm on amd64, not aarch64, if that matters.

**Comment by ikatson** [comment]
Can you please check 5.5.4, the latest stable one?

**Comment by yonas** [comment]
I checked [f7b22aa](https://github.com/ikatson/rqbit/commit/f7b22aa0aa85189b4199e0133cd457625e546a6e), it works.
